server:
  port: 8081


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://82.156.167.171/springboot_db
      username: root
      password: Abc@97923

  banner:
    location: banner.txt


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
